# syntax=docker/dockerfile:1
FROM rust:1.77-bookworm as builder

WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build --release && cp target/release/wasmcloud-operator .

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /app/wasmcloud-operator /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/wasmcloud-operator"]
