config:
  cluster:
    enabled: true
    replicas: 3
  leafnodes:
    enabled: true
  websocket:
    enabled: true
    port: 4223
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
    merge:
      domain: default
